# -*- coding: utf-8 -*-
"""Intelligent_System_Project.Ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqQL1u3lirrXsSrhza8uapr8SWBOMbWv
"""

!pip install deepface
import deepface
from deepface import DeepFace
import cv2 as cv
import imutils

image_type = ".jpg"
image_path = input("Please Enter the image text = ")+image_type    
# images should be in same directory 

img = cv.imread(image_path)

face_cascade = cv.CascadeClassifier('haarcascade_frontalface_default.xml')      #for detecting face


faces = face_cascade.detectMultiScale(img, 1.1, 4)


for (x, y, w, h) in faces:
  cv.rectangle(img, (x, y), (x+w, y+h), (256, 0, 0), 3)

#img = cv.resize(img,(900, 900))
img = imutils.resize(img, height=900)

result = DeepFace.analyze(img)  #Actions To Do ['gender']

from google.colab.patches import cv2_imshow
#cv2_imshow(img)

Gender=result['gender']

print(Gender)

org = (100, 100)


cv.putText(img,Gender,org,cv.FONT_HERSHEY_SIMPLEX,1,(256, 0, 0),2,cv.LINE_AA)

cv2_imshow(img)